### ISSUE TITLE
Use of Map/Set

### ISSUE THREAD

**Issue by smarr** [sblessing/chat-app#2]
While trying to debug the Newspeak/SOMns version of the benchmark, I am struggling to get comparable behavior. I believe, somewhere in my implementation is a bug, that I haven't yet identified.

Though, there are also a number of hurdles which make it hard to be sure we benchmark the same thing, and actually measure what we are interested in.

One of these issues is the used data structures, specifically:

```
type ClientMap is Map[U64, Client]
type FriendSet is SetIs[Client]
type ChatSet is SetIs[Chat]
type ClientSet is SetIs[Client]
```

https://github.com/sblessing/chat-app/blob/master/chat.pony#L10-L13

ClientMap:
```
for client in _clients.values() do
```
https://github.com/sblessing/chat-app/blob/master/chat.pony#L217
https://github.com/sblessing/chat-app/blob/master/chat.pony#L241
https://github.com/sblessing/chat-app/blob/master/chat.pony#L248

Here the issue is that iteration order over a map/dictionary is implementation defined.
Not to speak of the myriad different ways of implementing such a data structure.
Could we use a plain array instead and not worry about the memory use? (#clients * ptr size= 1024 * 8 = 8k)

FriendSet/ChatSet:
```
for friend in _friends.values() do
```
https://github.com/sblessing/chat-app/blob/master/chat.pony#L174
https://github.com/sblessing/chat-app/blob/master/chat.pony#L124

Again, implementation defined iteration order, which leads to different actors(clients) getting invited for a chat, or different chats being interacted with.
Given the low number of friends and chats, arrays with a linear search may work fine.

The same seems to be apply to the ClientSet:
https://github.com/sblessing/chat-app/blob/master/chat.pony#L75

Since these implementation defined ordering may affect communication patterns, which actors communicated, etc., i'd try to make sure these things are identical across implementations, and also deterministic, i.e., not relying for instance on hash values which may be derived from location in memory.

**Comment by sblessing** [comment]
This makes perfect sense, and is certainly the right thing to do when using value iterators for scanning the entire map/set.

My worries are lines like the following though:

https://github.com/sblessing/chat-app/blob/7adbdb216296c564b7a75c6cbac8a1be0003f23a/chat.pony#L100

https://github.com/sblessing/chat-app/blob/7adbdb216296c564b7a75c6cbac8a1be0003f23a/chat.pony#L131

https://github.com/sblessing/chat-app/blob/7adbdb216296c564b7a75c6cbac8a1be0003f23a/chat.pony#L142

https://github.com/sblessing/chat-app/blob/7adbdb216296c564b7a75c6cbac8a1be0003f23a/chat.pony#L215

https://github.com/sblessing/chat-app/blob/7adbdb216296c564b7a75c6cbac8a1be0003f23a/chat.pony#L231

where either checking if a client already exists or finding one to delete would become `O(n)` and with large chat app instances and lots of clients/chats this could scew the results quite a bit.

I am happy to move to an array-like structure for more determinism comparability, but I think this would only work nicely if the above is not a critical path.

**Comment by smarr** [comment]
Just to have it documented here:
 Indeed, as discussed, this might turn out to be an issue. Let's see what that changes give. Thanks!

**Comment by sblessing** [comment]
Commit a9f0f1b3b6329bab13c42e7d11a1c2305fd7c02f provides a version considering these points/concerns
