### ISSUE TITLE
Notion of a Turn?

### ISSUE THREAD

**Issue by smarr** [sblessing/chat-app#4]
What is the notion of a turn supposed to be?

Is a turn supposed to represent the same work, but repeated to have more measurements?
Or is a turn supposed to represent different work plans, and having multiple allows to judge whether performance is stable for similar but not identical "work plans"?

It it is the first, I would assume we need to reset random number generates, and possibly any kind of expanding data structure for each turn.

**Comment by sblessing** [comment]
It is the latter :)

**Comment by smarr** [comment]
Thanks
