### ISSUE TITLE
Non-universal Idioms: (val = val - 1) == oldVal

### ISSUE THREAD

**Issue by smarr** [sblessing/chat-app#5]
After too much debugging, I am now convinced that Pony has the following semantics: `(val = val - 1) == oldVal`.

This idiom is used in many places through out the code, but seems to be rather unusual compared to other languages. I am not aware of any language beside Pony that has these semantics.

I doubt that there's a huge performance benefit of the idiom, so, I would like to propose to avoid it in the interest of making it easier for people to understand the code, and port it to other languages.

In case that's acceptable, I am happy to provide a PR.

**Comment by sblessing** [comment]
I agree with you. This being not restricted to a Pony programmers domain, this should be make clearer. Happy to accept a PR.

**Comment by smarr** [comment]
Separate PR: #6
